name: wheels_up
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
      
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.15
  dio: ^5.7.0
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
    
  # Declare both assets under one assets section
  assets:
    - assets/wheelsup_logo.png
    - assets/jeep.png
    - assets/wheelsup_text_logo.svg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-variable.ttf
          style: normal
    
